import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    signOut: 'Sign Out',
    langToggle: 'اردو',
    // Login
    loginTitle: 'VeriLearn',
    loginSub: 'AI Learning Authenticity Evaluator',
    iAmA: "I am a...",
    student: 'Student',
    teacher: 'Teacher',
    continueGoogle: 'Continue with Google',
    orSignIn: 'or sign in manually',
    fullName: 'Full Name',
    namePlaceholder: 'Enter your name',
    email: 'Email',
    emailPlaceholder: 'your@email.com',
    signInAs: 'Sign in as',
    signingIn: 'Signing in...',
    termsNote: "By continuing you agree to VeriLearn's terms of use.",
    fillAll: 'Please fill all fields',
    // Student Dashboard
    welcomeBack: 'Welcome back',
    readyViva: 'Ready for your next viva?',
    totalVivas: 'Total Vivas',
    avgScore: 'Avg Score',
    aGrades: 'A Grades',
    dayStreak: 'Day Streak',
    startNewViva: 'Start a New Viva Session',
    startVivaDesc: 'Paste your assignment and get evaluated by AI in minutes.',
    startViva: 'Start Viva →',
    recentEvals: 'Recent Evaluations',
    subject: 'Subject',
    score: 'Score',
    grade: 'Grade',
    verdict: 'Verdict',
    date: 'Date',
    myResults: 'My Results',
    leaderboard: '🏆 Leaderboard',
    myLocation: '📍 My Location',
    settings: '⚙️ Settings',
    allowLocation: 'Allow location to track exam venue for authenticity verification.',
    getLocation: '📍 Get My Location',
    gettingLocation: '⏳ Getting location...',
    permDenied: 'Permission denied',
    // Teacher Dashboard
    teacherDash: 'Teacher Dashboard',
    monitorDesc: 'Monitor student evaluations in real-time.',
    totalStudents: 'Total Students',
    classAvg: 'Class Average',
    passed: 'Passed',
    failed: 'Failed',
    createAssignment: 'Create Assignment',
    createDesc: 'Generate AI viva questions for students',
    liveMonitor: 'Live Monitor',
    liveDesc: 'Watch student screens in real-time',
    studentActivity: 'Student Activity',
    inProgress: '⏳ In Progress',
    done: '✅ Done',
    allStudents: 'All Students',
    reports: 'Reports',
    print: '🖨 Print',
    publishing: 'Publish Assignment',
    assignTo: 'Assign To',
    allStudentsOpt: 'All Students',
    connectedStudents: 'Connected Students',
    noStudentsViva: 'No students currently in viva.',
    broadcasting: 'Broadcasting',
    startScreenShare: '📡 Start Screen Share',
    stopSharing: '⏹ Stop Sharing',
    startVoice: '🎤 Start Voice',
    // Viva Session
    startVivaSession: 'Start Viva Session',
    pasteAssignment: 'Paste your assignment and the AI will evaluate your understanding.',
    difficulty: 'Difficulty',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    assignmentText: 'Assignment Text',
    assignmentPlaceholder: 'Paste your assignment, code, essay, or any text here...',
    characters: 'characters',
    startVivaBtn: 'Start Viva →',
    need50: 'Need at least 50 characters',
    backToDash: '← Back to Dashboard',
    readingAssignment: 'Reading your assignment...',
    identifyingConcepts: 'Identifying key concepts...',
    checkingAI: 'Checking for AI signals...',
    preparingQuestions: 'Preparing viva questions...',
    generatingReport: 'Generating your report...',
    apiError: 'API Error',
    backendNote: 'Make sure backend is running: node server.js in /backend',
    questionOf: 'Question',
    of5: 'of 5',
    yourAnswer: 'Your Answer',
    answerPlaceholder: 'Explain in your own words...',
    listening: '🎤 Listening... speak now',
    submitAnswer: 'Submit Answer →',
    minChars: 'Minimum 30 characters required',
    // Report
    finalReport: 'Final Report',
    performanceMetrics: 'Performance Metrics',
    strengths: 'Strengths',
    weaknesses: 'Weaknesses',
    startNew: 'Start New Evaluation',
    conceptualClarity: 'Conceptual Clarity',
    answerDepth: 'Answer Depth',
    terminologyUsage: 'Terminology Usage',
    applicationAbility: 'Application Ability',
    pass: '✓ PASS',
    reviewRequired: '⚠ REVIEW REQUIRED',
    failResubmit: '✗ FAIL / RESUBMISSION',
    // Screen Share
    screenShareTitle: '📡 Screen Share (Student)',
    shareScreen: 'Share Your Screen',
    shareDesc: 'Teacher will see your screen live during the viva.',
    channelId: 'Channel ID',
    channelPlaceholder: 'Enter session channel ID',
    startSharing: '🖥️ Start Sharing',
    stopSharingBtn: '⏹ Stop Sharing',
    watchTitle: '👁️ Watch Student Screen (Teacher)',
    joinChannel: 'Join Channel',
    joinBtn: '▶ Join as Viewer',
    leaveBtn: '✕ Leave',
    screenLive: 'Screen is LIVE',
    waitingScreen: 'Waiting for student to share screen...',
  },
  ur: {
    // Navbar
    signOut: 'سائن آوٹ',
    langToggle: 'English',
    // Login
    loginTitle: 'ویری لرن',
    loginSub: 'اے آئی سیکھنے کی اصالت تشخیصگر',
    iAmA: 'میں ہوں...',
    student: 'طالب علم',
    teacher: 'استاد',
    continueGoogle: 'گوگل سے جاری رکھیں',
    orSignIn: 'یا دستی لاگ ان کریں',
    fullName: 'پورا نام',
    namePlaceholder: 'اپنا نام درج کریں',
    email: 'ای میل',
    emailPlaceholder: 'آپ کا ای میل',
    signInAs: 'لاگ ان کریں بطور',
    signingIn: 'لاگ ان ہو رہا ہے...',
    termsNote: 'جاری رکھ کر آپ ویری لرن کی شرائط سے متفق ہیں۔',
    fillAll: 'براہ کرم تمام خانے پُر کریں',
    // Student Dashboard
    welcomeBack: 'خوش آمدید',
    readyViva: 'اپنے اگلے وائیوا کے لیے تیار ہیں؟',
    totalVivas: 'کل وائیوا',
    avgScore: 'اوسط اسکور',
    aGrades: 'اے گریڈ',
    dayStreak: 'دن کی لڑی',
    startNewViva: 'نئی وائیوا سیشن شروع کریں',
    startVivaDesc: 'اپنا اسائنمنٹ پیسٹ کریں اور منٹوں میں اے آئی سے تشخیص پائیں۔',
    startViva: 'وائیوا شروع کریں ←',
    recentEvals: 'حالیہ تشخیص',
    subject: 'مضمون',
    score: 'اسکور',
    grade: 'گریڈ',
    verdict: 'فیصلہ',
    date: 'تاریخ',
    myResults: 'میرے نتائج',
    leaderboard: '🏆 لیڈر بورڈ',
    myLocation: '📍 میری لوکیشن',
    settings: '⚙️ ترتیبات',
    allowLocation: 'اصالت کی تصدیق کے لیے امتحان گاہ ٹریک کرنے کی اجازت دیں۔',
    getLocation: '📍 میری لوکیشن حاصل کریں',
    gettingLocation: '⏳ لوکیشن مل رہی ہے...',
    permDenied: 'اجازت نہیں دی گئی',
    // Teacher Dashboard
    teacherDash: 'استاد ڈیش بورڈ',
    monitorDesc: 'طلبہ کی تشخیص کو ریئل ٹائم میں مانیٹر کریں۔',
    totalStudents: 'کل طلبہ',
    classAvg: 'کلاس اوسط',
    passed: 'پاس',
    failed: 'فیل',
    createAssignment: 'اسائنمنٹ بنائیں',
    createDesc: 'طلبہ کے لیے اے آئی وائیوا سوالات بنائیں',
    liveMonitor: 'لائیو مانیٹر',
    liveDesc: 'طلبہ کی سکرینیں ریئل ٹائم میں دیکھیں',
    studentActivity: 'طلبہ کی سرگرمی',
    inProgress: '⏳ جاری ہے',
    done: '✅ مکمل',
    allStudents: 'تمام طلبہ',
    reports: 'رپورٹس',
    print: '🖨 پرنٹ',
    publishing: 'اسائنمنٹ شائع کریں',
    assignTo: 'کسے دیں',
    allStudentsOpt: 'تمام طلبہ',
    connectedStudents: 'متصل طلبہ',
    noStudentsViva: 'فی الحال کوئی طالب علم وائیوا میں نہیں۔',
    broadcasting: 'نشر ہو رہا ہے',
    startScreenShare: '📡 سکرین شیئر شروع کریں',
    stopSharing: '⏹ شیئر بند کریں',
    startVoice: '🎤 آواز شروع کریں',
    // Viva Session
    startVivaSession: 'وائیوا سیشن شروع کریں',
    pasteAssignment: 'اپنا اسائنمنٹ پیسٹ کریں اور اے آئی آپ کی سمجھ کا جائزہ لے گی۔',
    difficulty: 'مشکل سطح',
    beginner: 'ابتدائی',
    intermediate: 'درمیانی',
    advanced: 'اعلیٰ',
    assignmentText: 'اسائنمنٹ کا متن',
    assignmentPlaceholder: 'یہاں اپنا اسائنمنٹ، کوڈ، مضمون یا کوئی بھی متن پیسٹ کریں...',
    characters: 'حروف',
    startVivaBtn: 'وائیوا شروع کریں ←',
    need50: 'کم از کم ۵۰ حروف درکار ہیں',
    backToDash: '← ڈیش بورڈ پر واپس',
    readingAssignment: 'آپ کا اسائنمنٹ پڑھا جا رہا ہے...',
    identifyingConcepts: 'اہم تصورات شناخت ہو رہے ہیں...',
    checkingAI: 'اے آئی علامات چیک ہو رہی ہیں...',
    preparingQuestions: 'وائیوا سوالات تیار ہو رہے ہیں...',
    generatingReport: 'رپورٹ بنائی جا رہی ہے...',
    apiError: 'اے پی آئی خرابی',
    backendNote: 'یقینی بنائیں کہ بیک اینڈ چل رہا ہے: node server.js /backend میں',
    questionOf: 'سوال',
    of5: '۵ میں سے',
    yourAnswer: 'آپ کا جواب',
    answerPlaceholder: 'اپنے الفاظ میں سمجھائیں...',
    listening: '🎤 سن رہا ہوں... بولیں',
    submitAnswer: 'جواب جمع کریں ←',
    minChars: 'کم از کم ۳۰ حروف لکھنا ضروری ہے',
    // Report
    finalReport: 'حتمی رپورٹ',
    performanceMetrics: 'کارکردگی کے پیمانے',
    strengths: 'خوبیاں',
    weaknesses: 'کمزوریاں',
    startNew: 'نئی تشخیص شروع کریں',
    conceptualClarity: 'تصوراتی وضاحت',
    answerDepth: 'جواب کی گہرائی',
    terminologyUsage: 'اصطلاحی استعمال',
    applicationAbility: 'اطلاقی صلاحیت',
    pass: '✓ پاس',
    reviewRequired: '⚠ جائزہ ضروری',
    failResubmit: '✗ فیل / دوبارہ جمع کروائیں',
    // Screen Share
    screenShareTitle: '📡 سکرین شیئر (طالب علم)',
    shareScreen: 'اپنی سکرین شیئر کریں',
    shareDesc: 'وائیوا کے دوران استاد آپ کی سکرین لائیو دیکھ سکیں گے۔',
    channelId: 'چینل آئی ڈی',
    channelPlaceholder: 'سیشن چینل آئی ڈی درج کریں',
    startSharing: '🖥️ شیئر شروع کریں',
    stopSharingBtn: '⏹ شیئر بند کریں',
    watchTitle: '👁️ طالب علم کی سکرین دیکھیں (استاد)',
    joinChannel: 'چینل سے جڑیں',
    joinBtn: '▶ ناظر کے طور پر شامل ہوں',
    leaveBtn: '✕ چھوڑیں',
    screenLive: 'سکرین لائیو ہے',
    waitingScreen: 'طالب علم کے سکرین شیئر کرنے کا انتظار ہے...',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('vl-lang') || 'en');

  useEffect(() => {
    document.documentElement.setAttribute('lang', lang);
    document.documentElement.setAttribute('dir', lang === 'ur' ? 'rtl' : 'ltr');
    localStorage.setItem('vl-lang', lang);
  }, [lang]);

  const toggle = () => setLang(l => l === 'en' ? 'ur' : 'en');
  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggle, t, isUrdu: lang === 'ur' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
